const NOTION_DATABASE_ID_PERKS = process.env.NOTION_DATABASE_ID_PERKS;
const NOTION_DATABASE_ID_USERS = process.env.NOTION_DATABASE_ID_USERS;
const NOTION_DATABASE_ID_ACHIEVEMENTS =
  process.env.NOTION_DATABASE_ID_ACHIEVEMENTS;

const defaultExport = {
  NOTION_DATABASE_ID_PERKS,
  NOTION_DATABASE_ID_USERS,
  NOTION_DATABASE_ID_ACHIEVEMENTS,
};

export default defaultExport;
